### ISSUE TITLE
Logout crashes system

### ISSUE THREAD

**Issue by krusynth** [opengovfoundation/madison-editor#13]
It appears to be trying to overwrite the session, and in doing so it's not getting the old session for some reason - resulting in a duplicate insert that crashes the server.

**Comment by krusynth** [comment]
```
Executing (default): INSERT INTO `sessions` (`id`,`last_activity`,`payload`) VALUES ('psBHjHOpEym5tgZpdNXrMocP',1443459653,'{\"cookie\":{\"originalMaxAge\":86400000,\"expires\":\"2015-09-29T17:00:52.734Z\",\"httpOnly\":true,\"domain\":\".madison.localhost\",\"path\":\"/\"}}');
/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: ER_DUP_ENTRY: Duplicate entry 'psBHjHOpEym5tgZpdNXrMocP' for key 'sessions_id_unique'
    at Query.Sequence._packetToError (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    --------------------
    at Protocol._enqueue (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/mysql/lib/Connection.js:201:25)
    at module.exports.Query.run (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/dialects/mysql/query.js:26:17)
    at Function.<anonymous> (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:418:23)
    at null.<anonymous> (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/emitters/custom-event-emitter.js:105:15)
    at emit (events.js:107:17)
    at module.exports.CustomEventEmitter.emit (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
    at null.fct (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:224:26)
    at null.<anonymous> (/Users/krues8dr/Sites/etherpad.localhost/admin/node_modules/node-laravel-mysql-session/node_modules/sequelize/lib/emitters/custom-event-emitter.js:24:18)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by krusynth** [comment]
It looks like there was a race condition where logging out deleted the session, but when the login page loads again, there was still a session key in the cookie but no matching session - meanwhile the socket connection had already recreated the session in question, causing a duplicate insert.  Updating the dependency package to resolve this.
